services:
  - type: web
    name: working-days-api
    env: node
    plan: free
    nodeVersion: 20.19.4
    buildCommand: npm install && npm run build
    startCommand: cd src && node ../dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
